### ISSUE TITLE
Convert hardcoded variables to flags or environment variables.

### ISSUE THREAD

**Issue by alfonso-cabrera** [alfonso-cabrera/swapELB#1]
main.go has two hard coded variables, sourceElb and destElb. It would be ideal to have these variables be set by either flags passed when running the Go program or environment variables.

**Comment by dixonwille** [comment]
@alfonso-cabrera Would you like both? Check Env Variable first then overwrite with a flag it specified?

**Comment by huijari** [comment]
I made a [pull request](https://github.com/alfonso-cabrera/swapELB/pull/3) to resolve that issue 😉.

**Comment by alfonso-cabrera** [comment]
Issue solved - thanks!
